spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/potygames
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
