insert into user_addresses (id_user, favorite, billing_address, description, street, number, complement, neighborhood, city, state, country, zip_code) 
values 
(9, true, false, 'Lotlux', 'Transport', '3794', 'Road', 'Helodium blandowii (F. Weber & D. Mohr) Warnst.', 'Avignon', 'Tiliqua scincoides', 'France', '56339-834'),
(6, true, false, 'Zaam-Dox', 'Brentwood', '23825', 'Alley', 'Phacelia racemosa (Kellogg) Brandegee', 'Paokmotong Utara', 'Lamprotornis nitens', 'Indonesia', '15447-382'),
(4, true, false, 'Lotstring', 'Monument', '974', 'Alley', 'Mimosa quadrivalvis L. var. quadrivalvis', 'New Westminster', 'Conolophus subcristatus', 'Canada', '01139-484'),
(9, false, true, 'Lotstring', 'Dakota', '522', 'Place', 'Asplenium platyneuron (L.) Britton, Sterns & Poggenb.', 'Lakhdenpokhya', 'Lycaon pictus', 'Russia', '86744-009'),
(2, false, false, 'Vagram', 'Nova', '4', 'Pass', 'Darlingtonia Torr.', 'Działoszyce', 'Anser anser', 'Poland', '00818-942'),
(10, false, true, 'Treeflex', 'Anderson', '61396', 'Street', 'Archontophoenix H. Wendl. & Drude', 'Stockton', 'Phalaropus lobatus', 'United States', '62382-831'),
(3, true, false, 'Sonair', 'Eastwood', '753', 'Avenue', 'Lepanthes rupestris Stimson', 'Richmond', 'Nesomimus trifasciatus', 'United States', '69907-516'),
(1, true, true, 'Stringtough', 'Oak Valley', '02', 'Street', 'Cymopterus davisii R.L. Hartm.', 'Puck', 'Odocoileus hemionus', 'Poland', '47050-890'),
(1, false, true, 'Konklab', 'Swallow', '10017', 'Circle', 'Pycnanthemum virginianum (L.) T. Dur. & B.D. Jacks. ex B.L. Rob. & Fernald', 'Nama', 'Passer domesticus', 'Philippines', '54644-904'),
(4, false, true, 'Toughjoyfax', 'Clyde Gallagher', '2940', 'Park', 'Dicranum spadiceum J.E. Zetterst.', 'Gombe', 'Procyon cancrivorus', 'Uganda', '02284-176'),
(8, false, false, 'Aerified', 'Upham', '3072', 'Way', 'Cyperus surinamensis Rottb.', 'Santana do Paraíso', 'Vulpes cinereoargenteus', 'Brazil', '08237-504'),
(8, true, true, 'Ventosanzap', 'Sloan', '54756', 'Pass', 'Ochrosia haleakalae H. St. John', 'Xiaping', 'Lophoaetus occipitalis', 'China', '94961-968'),
(4, true, false, 'Namfix', 'New Castle', '758', 'Road', 'Penstemon newberryi A. Gray', 'Bibinje', 'Merops bullockoides', 'Croatia', '96544-604'),
(4, false, true, 'Ventosanzap', 'Dovetail', '516', 'Avenue', 'Cystopteris xwagneri R.C. Moran', 'Cầu Giát', 'Nyctanassa violacea', 'Vietnam', '71435-675'),
(4, true, true, 'Voyatouch', 'Farragut', '372', 'Junction', 'Jacquinia umbellata A. DC.', 'Noebana', 'Uraeginthus angolensis', 'Indonesia', '14709-691'),
(4, false, true, 'Konklux', 'Warbler', '9902', 'Lane', 'Punctelia rudecta (Ach.) Krog', 'Thạnh Phú', 'Cebus nigrivittatus', 'Vietnam', '77002-094'),
(5, false, true, 'Hatity', 'Moland', '3812', 'Center', 'Rhytidophyllum Mart.', 'Shuren', 'Vanellus chilensis', 'China', '62936-154'),
(3, false, false, 'Fix San', 'Moose', '99003', 'Junction', 'Viola xbissellii House', 'Karangdawa Barat', 'Phascogale calura', 'Indonesia', '58508-827'),
(2, false, true, 'Treeflex', '2nd', '675', 'Junction', 'Sphaeralcea procera Ced. Porter', 'Ketovo', 'Aonyx capensis', 'Russia', '54763-302'),
(10, false, true, 'Sonsing', 'Birchwood', '27', 'Pass', 'Eiglera flavida (Hepp) Hafellner', 'Mmaaf', 'Corvus albicollis', 'Indonesia', '61526-526');
